server:
  port: 9001

aws:
  es:
    accessKey: AKIAYQCAGGHQ4E2RMUWI
    secretKey: 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
    endPoint: https://search-es-demo-wi4pn3tr4glnex6y65jyznkqmy.us-east-1.es.amazonaws.com
    region: us-east-1

es:
  article:
    index:
      name: article
      type: _doc